# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0fb8d0de1aa0b885394a8665af60cf1ce87d1d36d5779d8e2829a838c23a84e0ccb8769d365ec34f3c89b06bdae4556d8eeec22d5761a40c19fa997bdd1d542

test:
  secret_key_base: 06a65ad009572ca4a255a078225bbc402784e8ca472194cb446faefe51a6003e52d66657c40b289f65d7fb2c966dd73f09cb0a35c2d26f2417f13a816dbc084e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
